PSIProjekt/PSIGameLibrary/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from games import views
from games.views import *
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
urlpatterns = [
    path('game', GameList.as_view()),
    path('game/<int:pk>', GameDetails.as_view()),
    path('ganre', GanreList.as_view()),
    path('user', UserList.as_view()),
    path('producer', ProducerList.as_view()),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', ProducerListView.as_view(), name='producer_list'),
    path('producer/<int:id>/', GamesListView.as_view(), name='games_list'),
    path('register/', registerPage, name='register'),
    path('profil/', ProfilePage.as_view(), name='profile'),
    path('profil_update/', ProfileUpdate.as_view(), name='profile_update'),
    path('admin/', admin.site.urls),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
       views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
       views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('koszyk/', views.cart_detail, name='cart_detail'),
    path('platnosc/', PaymentPage.as_view(), name='payment_page'),
    path('sukces/', SuccessOrder.as_view(), name='success_order'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

PSIProjekt/games/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from .views import *
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('game', GameList.as_view()),
    path('game/<int:pk>', GameDetails.as_view()),
    path('ganre', GanreList.as_view()),
    path('user', UserList.as_view()),
    path('producer', ProducerList.as_view()),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', ProducerListView.as_view(), name='producer_list'),
    path('producer/<int:id>/', GamesListView.as_view(), name='games_list'),
    path('register/', registerPage, name='register'),
    path('profil/', ProfilePage.as_view(), name='profile'),
    path('profil_update/', ProfileUpdate.as_view(), name='profile_update'),
    path('admin/', admin.site.urls),
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
       views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
       views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('koszyk/', views.cart_detail, name='cart_detail'),
    path('platnosc/', PaymentPage.as_view(), name='payment_page'),
    path('sukces/', SuccessOrder.as_view(), name='success_order'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

PSIProjekt/games/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class Uzytkownik(AbstractUser):
    last_update = models.DateTimeField(auto_now_add=True)



class Producent(models.Model):
    nazwa = models.CharField(max_length=45, blank=False, null=False)
    rok_zalozenia = models.DateField()
    siedziba = models.CharField(max_length=45, blank=False, null=False)
    ilosc_czlonkow = models.IntegerField()
    image = models.ImageField('Zdjęcie', blank=True)

    def __str__(self):
        return self.nazwa


class Gatunek(models.Model):
    nazwa = models.CharField(max_length=45, blank=False, null=False)
    def __str__(self):
        return self.nazwa


class Gra(models.Model):
    name = models.CharField(max_length=20, blank=False)
    opis = models.CharField(max_length=200, blank=False)
    pegi = models.CharField(max_length=20, blank=False)
    ocena = models.CharField(max_length=20, blank=False)
    price = models.FloatField('Cena Gry', default=0, blank=True)
    image = models.ImageField('Zdjęcie', blank=True)
    rok_produkcji = models.DateField()
    idGatunku = models.ForeignKey(Gatunek, null=False, blank=False, on_delete=models.DO_NOTHING)
    idProducenta = models.ForeignKey(Producent, null=False, blank=False, on_delete=models.DO_NOTHING)


class Order(models.Model):
    name = models.CharField('Imię i Nazwisko', max_length=200, default='', blank=True)
    address = models.CharField('Adres', max_length=200, default='', blank=True)
    address_client = models.ForeignKey(
        Uzytkownik,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='client',
    )

    def __str__(self):
        return f'Zamówienie #{self.id}'



class CartItem(models.Model):
    order = models.ForeignKey(
        Order,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    product = models.ForeignKey(
        Gra,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    quantity = models.IntegerField('Ilosc')

PSIProjekt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <meta charset="UTF-8">
  <title>Games Store</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}" />
</head>
<body style="height:100%;background-color:#C8C8C8">
{% block header %}
  {% include 'header.html' %}
{% endblock %}
<div class="container">
{% block content %}
{% endblock %}
</div>
{% block footer %}
{% endblock %}
<script src="{% static 'js/jquery-3.5.1.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

PSIProjekt/templates/cart.html
{% extends 'base.html' %}
{% load edittags %}
{% block content %}
  <div class="card border-0 shadow" style="background-color:#E2E2E2;padding-bottom: 15px;">
    {% if request.session.cart %}
  <h2 class="text-center">Koszyk</h2>
      <a style="position:absolute;top:5px;right:20px;" class="btn btn-danger mt-2" href="{% url 'cart_clear' %}">Wyczyść koszyk</a>
{% for key,value in request.session.cart.items %}
  <hr/>
  <div class="row" style="padding-top:10px;">
  <div class="col-xl-2">
    {% if value.image %}
  <img src="{{value.image}}" height="100px" width="100px"/>
    {% endif %}
  </div>
  <div class="col-xl-2">
  <h5>{{value.tytul}}</h5>
  </div>
  <div class="col-xl-2">
  <h5>Ilość</h5>
    {{value.quantity}}
  </div>
  <div class="col-xl-2">
  <h5>Koszt</h5>
    {% multiply value.quantity value.price %} zł
  </div>
  <div class="col-xl-2" style="padding-top: 15px">
  <a href="{% url 'item_increment' key %}">
<span class="material-icons" style="margin-left: 10px" >
  add
</span>
    </a>
    {% if value.quantity > 1 %}
    <a href="{% url 'item_decrement' key %}">
      {% else %}
      <a href="{% url 'item_clear' key %}">
        {% endif %}
<span class="material-icons" style="margin-left: 10px" >
  remove
</span>
    </a>
  </div>
  <div class="col-xl-2" style="padding-top: 15px">
  <a href="{% url 'item_clear' key %}">
<span class="material-icons" style="margin-left: 10px" >
  deletes
</span>
    </a>
  </div>
</div>

    {% endfor %}
      <hr/>

  <h4 class="text-right">Całkowita wartość: {% checksum request.session.cart.items %} zł</h4>


  {% else %}
      <p><h2 class="text-center">Koszyk jest pusty. Zapraszamy do<a href="{% url 'producer_list' %}"> zakupów!</a></h2></p>
  {% endif %}
  </div>
  {% if request.session.cart %}
<a class="btn btn-success" href="{% url 'payment_page' %}" style="float: right">Przejdź do podsumowania</a>
  {% endif %}
{% endblock %}
{% block extra_js %}
  <script type="text/javascript">
  function Suma(dict){
      for (const [key, value] of Object.entries(dict)) {
          console.log(key, value);
      }
  }
  $('document').ready(Suma({{ request.session.cart.items }}));
  </script>
{% endblock %}

PSIProjekt/templates/gameslist.html
{% extends 'base.html' %}
{% block content %}
  <div class="card border-0 shadow" style="background-color:#E2E2E2;">
    <h2 class="text-center">Producent {{ producent.name }}</h2>
{% for gra in object_list %}
  <div class="row" style="padding-top:10px;">
  <div class="col-xl-3">
    {% if gra.image %}
  <img src="{{gra.image.url}}" height="100px" width="100px"/>
    {% endif %}
  </div>
  <div class="col-xl-3">
  <h4>{{gra.name}}</h4>
  {{gra.price}} zł
      Pegi: {{gra.pegi}}
    {{gra.opis}}
  </div>
    <div class="col-xl-2" style="padding-top: 15px">
    <form method="POST" id="add_form" action="{% url 'cart_add' gra.id %}">
      {% csrf_token %}
    <a class="btn btn-success" type="submit" id="{{ gra.id }}" onclick="SendForm(event,this)">Dodaj do koszyka</a>
      </form>
  </div>
</div>
    {% endfor %}
  <div class="row">
  <div class="col-xl-4 offset-xl-5">
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
  </div>
<a href="/" style = "text-align: center">Strona główna</a>
  </div>
  <div id="snackbar">
  </div>
{% endblock %}
{% block extra_js %}
  <script type="text/javascript">
  function SendForm(event, element) {
          event.preventDefault()
          const ids = element.id
          $.ajax({
              method: "POST",
              url: '/cart/add/'+ids+'/',
              data: $('#add_form').serialize(),
              success: function (response) {
                  console.log(response);
                  $('#snackbar').html(response.status);
                  $('#snackbar').addClass("show");
                  setTimeout(function () {
                      $('#snackbar').removeClass("show");
                  }, 3000);
              },
          })
      }
  </script>
{% endblock %}

PSIProjekt/templates/header.html
{% load static %}
<header class="header dark-topbar header-sticky" style="position:sticky;top:-0.5px;z-index: 999;height:auto;">
    <nav class="navbar navbar-expand-lg" style="min-height: 70px;">
        <div class="container navbar-container">
            <a href="{% url 'producer_list' %}">
                <img src="{% static 'images/Console-PNG-Image.png'%}" alt="logo" width="100px" height="100px"/>
            </a>
            <div class="collapse navbar-collapse align-items-center justify-content-end" id="navbar_main">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'profile' %}" class="nav-link fw-6"
                           style="padding-left:10px;padding-right:10px;font-size: 21px;" href="#" aria-haspopup="true"
                           aria-expanded="false">Profil</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'cart_detail' %}" class="nav-link fw-6"
                           style="padding-left:10px;padding-right:10px;font-size: 21px;" href="#" aria-haspopup="true"
                           aria-expanded="false">Koszyk</a>
                    </li>
                    a
                    <li class="nav-item">
                        <a href="{% url 'logout' %}" class="nav-link fw-6"
                           style="padding-left:10px;padding-right:10px;font-size: 21px;" href="#" aria-haspopup="true"
                           aria-expanded="false">Wyloguj</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'login' %}" class="nav-link fw-6"
                           style="padding-left:10px;padding-right:10px;font-size: 21px;" href="#" aria-haspopup="true"
                           aria-expanded="false">Zaloguj</a>
                    </li>
                    <li>
                        <a href="{% url 'register' %}" class="nav-link fw-6"
                           style="padding-left:10px;padding-right:10px;font-size: 21px;" href="#" aria-haspopup="true"
                           aria-expanded="false">Rejestracja</a>
                    </li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

PSIProjekt/templates/landing_page.html
{% extends 'base.html'%}
{% block content %}
Witamy w Games Store
{% endblock %}

PSIProjekt/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="col-xl-4 offset-xl-4 card border-0 shadow" style="background-color:#E2E2E2;">
<h3 class="text-center">Logowanie</h3>
  <form id="signin_form" method="post">
            <div class="modal-body">
              {% csrf_token %}
              {% if form.errors %}
                <div id="snackbar" style="visibility: visible">Niepoprawne dane
                </div>
              {% endif %}

              <p>
              <label for="username">Nazwa użytkownika/Email</label><br/>
              <input type="email" name="username" class="form-control" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
              </p>
              <p>
              <label for="password">Hasło</label><br/>
              <input type="password" name="password" class="form-control" autocomplete="current-password" required="" id="id_password"/>
              </p>
              <div class="form-group d-flex justify-content-left">

                <button type="submit"
                        class="btn btn-primary mt-4">Zaloguj
                </button>
              </div>
             Nie masz konta? <a href="{% url 'register' %}"> Zarejestruj</a>
            </div>
          </form>
  </div>
{% endblock %}
{% block extra_js %}
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <script type="text/javascript">
      function RemoveSnackbar(){
          setTimeout(function () {
              $('#snackbar').css('visibility', 'hidden');
          }, 3000);
      }
      $('document').ready(RemoveSnackbar);
  </script>
{% endblock %}

PSIProjekt/templates/logout.html
{% extends 'base.html' %}
{% block content %}
  <h1>Wylogowałeś sie</h1>
{% endblock %}

PSIProjekt/templates/payment.html
{% extends 'base.html'%}
{% load static %}
{% load edittags %}
{% block content%}

<div class="card border-0 shadow col-xl-8 offset-xl-3"
     style="background-color:#E2E2E2; padding-top: 30px; margin: 30px; margin-left: -30%">
    <form method="post">
        {% csrf_token %}
        <label for="name">Imię i Nazwisko:</label><br>
        <input class="form-control" type="text" id="name" name="name" value="{{user.first_name}} {{user.last_name}}"
               style="width: 75%"><br>
        <label for="address">Adres</label><br>
        <input class="form-control" type="text" id="address" name="address" value="{{user.address}}"
               style="width: 75%"><br>
        <p>Wybierz metodę płatności:</p>
        <table style="margin-left: none; margin-right: 50px;">
            <tr>
        <td><input type="image" alt="submit" src="{% static 'images/paypal.png'%}" style=" width: 100px; height: 100px; margin-left: 150px"></td>
        <td><input type="image" alt="submit" src="{% static 'images/blik.png'%}" style=" width: 150px; height: 100px; margin-left: 150px"></td>
            </tr>
        </table>

    </form>
</div>
<div class="card border-0 shadow col-xl-10 offset-xl-3" style="background-color:#E2E2E2;padding-bottom: 15px; margin-left: 40%; margin-top: -44.1%">
    {% if request.session.cart %}
    <h2 class="text-center">Koszyk</h2>
    {% for key,value in request.session.cart.items %}
    <hr/>
    <div class="row" style="padding-top:10px;">
        <div class="col-xl-2">
            {% if value.image %}
            <img src="{{value.image}}" height="100px" width="100px"/>
            {% endif %}
        </div>
        <div class="col-xl-2">
            <h5>{{value.name}}</h5>
        </div>
        <div class="col-xl-2">
            <h5>Ilość</h5>
            {{value.quantity}}
        </div>
        <div>
            <h5>Koszt</h5>
            {% multiply value.quantity value.price %} zł
        </div>

    </div>


    {% endfor %}

    <hr/>


    <h4 class="text-right">Całkowita wartość: {% checksum request.session.cart.items %} zł</h4>

    {% else %}
    <p>
    <h2 class="text-center">Koszyk jest pusty. Zapraszamy do<a href="{% url 'restaurant_list' %}"> zakupów!</a></h2></p>
    {% endif %}

</div>
<div>
</div>
{% endblock %}

PSIProjekt/templates/producers_list.html
{% extends 'base.html' %}
{% block content %}

  <div class="card border-0 shadow" style="background-color:#E2E2E2;">
  <h2 class="text-center">Lista Producentów</h2>

{% for producent in object_list %}
  <a href="{% url 'games_list' producent.id %}">
  <div class="row" style="padding-top:10px;">
  <div class="col-xl-2">
    {% if producent.image %}
  <img src="{{producent.image.url}}" height="100px" width="100px"/>
    {% endif %}
  </div>
  <div>
  <h4>{{producent.nazwa}}</h4>
  {{producent.siedziba}}
  </div>
</div>
  </a>
    {% endfor %}
  <div class="row">
  <div class="col-xl-4 offset-xl-5">
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
</div>
  </div>

  </div>
{% endblock %}

PSIProjekt/templates/profile.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
  <div id="form_div" class="col-lg-6 offset-xl-3 card border-0 shadow" style="background-color:#E2E2E2;">
{% include 'profile_update.html' %}
  </div>
  </div>
  <div id="snackbar">
  Zaktualizowano profil
  </div>
{% endblock %}
{% block extra_js %}
  <script type="text/javascript">
  $('document').ready(
      $.ajax({
          method: "GET",
          url: '{% url 'profile_update' %}',
          success: function (response) {
              $('#form_div').html(response);
          },
          error: function (response) {
              console.log(response)
          }
      })
  );
  function PostWizard(event) {
          event.preventDefault()
          $.ajax({
              method: "POST",
              url: '{% url 'profile_update' %}',
              data: $('#profile_form').serialize(),
              success: function (response) {
                  $('#form_div').html(response);
                  console.log(response);
                  if(!response.includes('errorlist')) {
                      $('#snackbar').addClass("show");
                      setTimeout(function () {
                          $('#snackbar').removeClass("show");
                      }, 3000);
                  }
              },
              error: function (response) {
                  console.log(response)
              }
          })
      }
  </script>
{% endblock %}

PSIProjekt/templates/profile_update.html
<h3 class="text-center">Twoje dane:</h3>
<form method="POST" id="profile_form">
  <div class="modal-body">
    {% csrf_token %}
    <p>
      <label for="first_name">Imię</label><br/>
      <input type="text" name="first_name" class="form-control" autocapitalize="none" maxlength="150" required="" value="{{ form.first_name.value }}"
             id="id_first_name">
    </p>
    <p>
      <label for="last_name" class>Nazwisko</label><br/>
      <input type="text" name="last_name" class="form-control" autocapitalize="none" maxlength="150" required="" value="{{ form.last_name.value }}"
             id="id_last_name">
    </p>
    <p>
      <label for="email">Email</label><br/>
      <input type="text" name="email" class="form-control" autocapitalize="none" maxlength="150" required="" value="{{ form.email.value }}"
             id="id_email">
    {{ form.errors.email }}</p>
    <p>
      <label for="address">Adres</label><br/>
      <input type="text" name="address" class="form-control" autocapitalize="none" maxlength="150" required="" value="{{ form.address.value }}"
             id="id_address">
    </p>
    <p>
      <label for="phone_number">Numer telefonu</label><br/>
      <input type="text" name="phone_number" class="form-control" autocapitalize="none" maxlength="150" required="" value="{{ form.phone_number.value }}"
             id="id_phone_number">
    </p>
    <div class="form-group d-flex justify-content-left">
      <button type="submit"
              onclick=" PostWizard(event);" style="width:100%;"
              class="btn btn-primary mt-4">Zapisz
      </button>
    </div>
  </div>
</form>

PSIProjekt/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="col-xl-4 offset-xl-4 card border-0 shadow" style="background-color:#E2E2E2;">
<h3 class="text-center">Rejestracja</h3>
<form method="POST">
  <div class="modal-body">
{% csrf_token %}
  <p>
              <label for="username">Nazwa użytkownika</label><br/>
              <input type="text" name="username" class="form-control" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">

  {{ form.errors.username }}</p>
  <p>
              <label for="username">Email</label><br/>
              <input type="email" name="email" class="form-control" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username">
              {{ form.errors.email }}
  </p>
              <p>
              <label for="password">Hasło</label><br/>
              <input type="password" name="password1" class="form-control" required="" id="id_password"/>
              {{ form.errors.password1 }}
              </p>
  <p>
              <label for="password">Powtórz hasło</label><br/>
              <input type="password" name="password2" class="form-control" required="" id="id_password"/>
    {{ form.errors.password2 }}
              </p>
              <div class="form-group d-flex justify-content-left">
                <p>
                <button type="submit"
                        class="btn btn-primary mt-4">Rejestruj
                </button>
              </div>
    Masz konto? <a href="{% url 'login' %}"> Zaloguj</a>
  </div>

</form>
</div>
{% endblock %}

PSIProjekt/templates/success_order.html
{% extends 'base.html' %}
{% load edittags %}
{% block content %}
  <div class="card border-0 shadow" style="background-color:#E2E2E2;padding-bottom: 15px;">
      <p><h2 class="text-center">Złożono zamówienie zapraszamy do dalszych <a href="{% url 'producer_list' %}">zakupów!</a></h2></p>
  </div>
{% endblock %}
{% block extra_js %}
{% endblock %}